In [ ]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;
import seaborn as sns;

In [ ]:
df = pd.read_csv("healthcare_dataset.csv")

In [ ]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD10 I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD10 J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD10 E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD10 J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD10 S52,8500.0,25-01-2026

In [ ]:
df.columns

Index(['Patient_ID', 'Gender', 'Age', 'Medical_Condition', 'Admission_Date',
       'Admission_Type', 'Medical_Code', 'Billing_Amount', 'Discharge_Date'],
      dtype='object')

In [ ]:
df.isnull()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Patient_ID            0
Gender                0
Age                   0
Medical_Condition     0
Admission_Date        0
Admission_Type        0
Medical_Code         15
Billing_Amount        0
Discharge_Date        0
dtype: int64

In [ ]:
df['Medical_Code'].isnull().sum()

np.int64(15)

In [ ]:
df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Admission_Date']

/tmp/ipykernel_2665/4191176909.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Admission_Date']=pd.to_datetime(df['Admission_Date'])

0     2026-01-15
1     2026-01-16
2     2026-01-16
3     2026-01-17
4     2026-01-17
         ...
495   2026-09-20
496   2026-09-20
497   2026-09-21
498   2026-09-21
499   2026-09-22
Name: Admission_Date, Length: 500, dtype: datetime64[ns]

In [ ]:
df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])
df['Discharge_Date']

/tmp/ipykernel_2665/3028613730.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])

0     2026-01-20
1     2026-01-22
2     2026-01-18
3     2026-01-19
4     2026-01-25
         ...
495   2026-09-23
496   2026-09-24
497   2026-09-25
498   2026-09-23
499   2026-09-26
Name: Discharge_Date, Length: 500, dtype: datetime64[ns]

In [ ]:
df['Admission_Type'] = (
df['Admission_Type']
                         .str.strip()
                         .str.lower()
)

In [ ]:
pd.crosstab(df['Admission_Type'],df['Admission_Date'])

Admission_Date  emergency  routine  urgent
Admission_Type
Emergency             188        0       0
Routine                 0      196       0
Urgent                  0        0     116

In [ ]:
gender_df = pd.crosstab(df['Admission_Type'],df['Admission_Date'])

In [ ]:
df["Admission_Type"].value_counts()

Admission_Type
Routine      196
Emergency    188
Urgent       116
Name: count, dtype: int64

In [ ]:
df["Billing_Amount"].describe()

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64

In [ ]:
df["Billing_Amount"]

0       4500.0
1       6700.5
2       3200.0
3       5800.0
4       8500.0
        ...
495     9800.0
496     9400.0
497    14200.0
498     4900.0
499    13900.0
Name: Billing_Amount, Length: 500, dtype: float64

In [41]:

df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
display(df['Hospital_Stay_Days'].describe())

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Hospital_Stay_Days, dtype: float64

In [ ]:
pd.crosstab(df["Medical_Condition"],df["Gender"])

Gender                   Female  Male
Medical_Condition
Allergic Reaction            14     1
Anxiety Disorder              2     7
Appendicitis                  8    25
Asthma                        8    11
Back Pain                     5    15
COPD                         16    18
Diabetes Type 1              12     3
Diabetes Type 2               6    10
Fracture                      7    15
Gallstones                    3    12
Gastritis                    11    10
Heart Attack                 15    12
Heart Failure                10    20
Hypertension                 19     9
Hypothyroidism                1     0
Kidney Stone                 10    18
Migraine                      6     0
Osteoarthritis                6     6
Osteoporosis                  8     4
Parkinson's Disease           9    10
Pneumonia                    18    13
Pregnancy                    14     2
Skin Infection               12     8
Stroke                       16    17
Urinary Tract Infection      14     4